### PR TITLE
add vote for spark connector repo

### PR DESCRIPTION
**Pull request by whhe**
## Summary

We'd like to add a repo for Spark connector to support data reading and writing to OceanBase database.

 @wnh5 @yuanoOo  @xxsc0529 Please comment on this thread when you're available.

### CODE REVIEW

**Comment by xxsc0529** [comment]
> ## 概括
> 我们想添加一个 Spark 连接器的 repo，以支持对 OceanBase 数据库的数据读写。
> 
> @wnh5 @yuanoOo @xxsc0529当您有空时请对此主题发表评论。
> 
> ## 解决方案描述

+1

**Comment by xxsc0529** [comment]
> ## Summary
> We'd like to add a repo for Spark connector to support data reading and writing to OceanBase database.
> 
> @wnh5 @yuanoOo @xxsc0529 Please comment on this thread when you're available.
> 
> ## Solution Description

+1

**Comment by yuanoOo** [comment]
+1

**Comment by wnh5** [comment]
+1

**Comment by hnwyllmm** [comment]
You should request @caifeizhi or @longdafeng for approval.

**Review by caifeizhi — APPROVED** [review]
LGTM

**Comment by hnwyllmm** [comment]
The repo was created: https://github.com/oceanbase/spark-connector-oceanbase

@yuanoOo, @wnh5 and @xxsc0529 , please check your github email to accept the invitation.

**Pull request merged**
