### PR TITLE
vote for compilation sig

### PR DESCRIPTION
**Pull request by LINxiansheng**
## Summary

vote for create compilation sig

### CODE REVIEW

**Comment by Teingi** [comment]
LGTM

**Review by Teingi — APPROVED** [review]

**Review by hnwyllmm — APPROVED** [review]
LGTM

**Comment by hnwyllmm** [comment]
接下来邀请 @caifeizhi 和 @MizuhaHimuraki 审批就完全通过了。

**Review by caifeizhi — APPROVED** [review]
LGTM

**Comment by MizuhaHimuraki** [comment]
LGTM

**Comment by Teingi** [comment]
Congratulations, the vote for the establishment of the SIG has been passed by all maintainers.

**Pull request merged**
